### ISSUE TITLE
Errors in logagg-fs

### ISSUE THREAD

**Issue by supriyopaul** [deep-compute/logagg-collector#4]
#### In fuse log file
- {"id": "20181130T062211_44a24027f46811e8a511b3d7862648ad", "type": "log", "host": "visibility", "timestamp": "2018-11-30T06:22:11.369251Z", "level": "error", "event": "logit_exception_getattr", "exception": "Traceback (most recent call last):\n  File \"/root/Supriyo/venvs/collector/lib/python3.6/site-packages/logagg_fs/mirrorfs.py\", line 39, in _fn\n    r = fn(*args, **kwargs)\n  File \"/root/Supriyo/venvs/collector/lib/python3.6/site-packages/logagg_fs/mirrorfs.py\", line 172, in getattr\n    return os.lstat(path)\nFileNotFoundError: [Errno 2] No such file or directory: '/.logcache/mirror/journal/39c230dd4f6348fa9fdf4e1c4cb57713/fss'"}
- {"args": ["<logagg_fs.fs.LogaggFSFile object at 0x7f7d9c4e0cc0>", "Nov 30 07:22:46 visibility sshd[1696]: error: Failed to write to /var/log/btmp: Invalid argument\n", 42284695], "kwargs": {}, "id": "20181130T062246_5a30f52bf46811e8a524b3d7862648ad", "type": "log", "host": "visibility", "timestamp": "2018-11-30T06:22:46.192099Z", "level": "debug", "event": "write"}
#### In syslog
Nov 30 07:28:22 visibility kernel: [  627.451950] systemd-journald[394]: Failed to open system journal: Invalid argument
Nov 30 07:28:23 visibility kernel: [  628.522916] systemd-journald[394]: Failed to open system journal: Invalid argument
Nov 30 07:28:23 visibility kernel: [  628.539794] systemd-journald[394]: Failed to open system journal: Invalid argument
Nov 30 07:28:23 visibility kernel: [  628.554968] systemd-journald[394]: Failed to open system journal: Invalid argument
Nov 30 07:28:23 visibility kernel: [  628.567309] systemd-journald[394]: Failed to open system journal: Invalid argument

**Comment by supriyopaul** [comment]
Not working on this repo Now.

**Comment by supriyopaul** [comment]
Will work on this later

**Comment by jaswanth098** [comment]
not working on this actively

**Comment by sundarrajan78** [comment]
@jaswanth098 Is this a priority now or can be moved for later weeks?

**Comment by sundarrajan78** [comment]
Un assigned Supriyo and assigned @shivam05011996

**Comment by shivam05011996** [comment]
Low priority

**Comment by shivam05011996** [comment]
Low priority

**Comment by shivam05011996** [comment]
Planning to work on this in the near future. Low priority.

**Comment by shivam05011996** [comment]
Not gonna be taken up soon. Snoozing for next 3 months

**Comment by sundarrajan78** [comment]
Snoozing for 3 months

**Comment by sundarrajan78** [comment]
@shivam05011996 Post update

**Comment by prashanthellina** [comment]
Snoozing

**Comment by shivam05011996** [comment]
Low priority.
